apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  template:
    spec:
      containers:
        - name: backend-api
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/fpl
            - name: SPRING_DATASOURCE_USERNAME
              value: fpl
            - name: SPRING_DATASOURCE_PASSWORD
              value: fpl-ci-password
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: FLASK_API_URL
              value: http://flask-ml:5001
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: INTERNAL_API_TOKEN
              value: ci-internal-token
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
