apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  template:
    spec:
      containers:
        - name: backend-api
          envFrom:
            - secretRef:
                name: supabase-db
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: FLASK_API_URL
              value: http://flask-ml:5001
            - name: REDIS_HOST
              value: redis
            - name: INTERNAL_API_TOKEN
              value: dev-internal-token
            - name: JWT_SECRET
              value: your-jwt-secret-change-in-production
